// <auto-generated />
namespace IA_E_commerce_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class testrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201904131508266_testrelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
